In [22]:
import pandas as pd
import sqlite3

In [25]:
db_path = r'job_applications.db'
conn = sqlite3.connect(db_path)
                                                              
query = '''
SELECT *
FROM job_applications app
left join job_descriptions desc on (app.application_id = desc.description_id)
'''

pd.read_sql(query, conn)

# conn.close()

,record_id,application_id,company,job_title,applied,application_date,resume_used,referred,status,notes,created_at,updated_at,current_indicator,description_id,job_posting_link
0,1,1,Test4,Test5,1,2024-10-29,None,1,Applied,,2024-10-27 12:45:10.409214,2024-10-27 12:46:23.515577,0,1,https://github.com/SpencerRWood/job-applier
1,2,2,Test5,Test6,1,2024-10-29,None,1,Applied,,2024-10-27 12:45:28.569407,None,1,2,https://github.com/SpencerRWood/job-applier
2,3,1,Test4,Test5,1,2024-10-29,None,1,Offered,,2024-10-27 12:45:10.409214,2024-10-27 12:46:23.518753,1,1,https://github.com/SpencerRWood/job-applier